import { objectToReverseMap } from "../utils/object-to-reverse-map.js";

export const Colors = Object.freeze({
  __proto__: null,
  None         : 0x00,
  DarkGray     : 0x01,
  Gray         : 0x02,
  LightGray    : 0x03,
  DarkSilver   : 0x04,
  Silver       : 0x05,
  LightSilver  : 0x06,
  DarkBrown    : 0x07,
  Brown        : 0x08,
  LightBrown   : 0x09,
  DarkBeige    : 0x0A,
  Beige        : 0x0B,
  LightBeige   : 0x0C,
  DarkRed      : 0x0D,
  Red          : 0x0E,
  LightRed     : 0x0F,
  DarkOrange   : 0x10,
  Orange       : 0x11,
  LightOrange  : 0x12,
  DarkYellow   : 0x13,
  Yellow       : 0x14,
  LightYellow  : 0x15,
  DarkGreen    : 0x16,
  Green        : 0x17,
  LightGreen   : 0x18,
  DarkBlue     : 0x19,
  Blue         : 0x1A,
  LightBlue    : 0x1B,
  DarkPurple   : 0x1C,
  Purple       : 0x1D,
  LightPurple  : 0x1E,
  DarkMagenta  : 0x1F,
  Magenta      : 0x20,
  LightMagenta : 0x21,
});

export const ColorNames = objectToReverseMap(Colors);
