export const Empty =     { size: [1, 1, 1], index: 0 };

export const Folder = {
  "Folder Unknown":      { size: [1, 1, 1], index: 382 },
  "Folder Empty":        { size: [1, 1, 1], index: 415 },
  "Folder Locked":       { size: [1, 1, 1], index: 416 },
};

export const Stock = {
  "Stone Block":         { size: [1, 1, 1], index: 1 },
  "Bricks":              { size: [1, 1, 1], index: 2 },
  "Grass":               { size: [1, 1, 1], index: 3, variations: 2 },
  "Dirt":                { size: [1, 1, 1], index: 5 },
  "Wood":                { size: [1, 1, 1], index: 6, variations: 3 },
  "Dirt Slab":           { size: [1, 1, 1], index: 384 },
  "Steel":               { size: [1, 1, 1], index: 385 },
  "Arch":                { size: [1, 2, 1], index: 386 },
  "Box":                 { size: [1, 1, 1], index: 388 },
  "Physics Box":         { size: [1, 1, 1], index: 425 },
  "Physics Sphere":      { size: [1, 1, 1], index: 426 },
  "Pass Through":        { size: [1, 1, 1], index: 448 },
  "$Dirt":               { size: [1, 1, 1], index: 490 },
  "Flowers":             { size: [1, 1, 1], index: 494 },
  "Foliage":             { size: [1, 1, 1], index: 495, variations: 2 },
  "Foliage Top":         { size: [1, 1, 1], index: 497 },
  "Foliage Bottom":      { size: [1, 1, 1], index: 498 },
  "Foliage Slab":        { size: [1, 1, 1], index: 499 },
  "Shrub":               { size: [1, 1, 1], index: 500 },
  "Stone":               { size: [1, 1, 1], index: 501, variations: 2 },
  "Stone Top":           { size: [1, 1, 1], index: 503 },
  "Stone Bottom":        { size: [1, 1, 1], index: 504 },
  "Stone Slab":          { size: [1, 1, 1], index: 505 },
  "Stone Pillar":        { size: [1, 1, 1], index: 506 },
  "Stone Half":          { size: [1, 1, 1], index: 507 },
  "Wood Half":           { size: [1, 1, 1], index: 508, variations: 4 },
  "Stick":               { size: [1, 1, 1], index: 512, variations: 15 },
  "Marker":              { size: [1, 1, 1], index: 536 },
  "Script Block":        { size: [1, 1, 1], index: 545 },
  "Sphere":              { size: [1, 1, 1], index: 546 },
  "Slate":               { size: [1, 1, 1], index: 547, variations: 2 },
  "Slate NE":            { size: [1, 1, 1], index: 549 },
  "Slate NW":            { size: [1, 1, 1], index: 550 },
  "Slate SE":            { size: [1, 1, 1], index: 551 },
  "Slate SW":            { size: [1, 1, 1], index: 552 },
  "Slate Top":           { size: [1, 1, 1], index: 553 },
  "Slate Bottom":        { size: [1, 1, 1], index: 554 },
  "Particle":            { size: [1, 1, 1], index: 555 },
};

export const Script = {
  "Comment":             { size: [1, 1, 1], index: 15 },
  "Inspect Number":      { size: [2, 1, 2], index: 16 },
  "Inspect Vector":      { size: [2, 1, 2], index: 20 },
  "Inspect Rotation":    { size: [2, 1, 2], index: 24 },
  "Inspect Truth":       { size: [2, 1, 2], index: 28 },
  "Inspect Object":      { size: [2, 1, 2], index: 32 },
  "Number":              { size: [2, 1, 1], index: 36 },
  "Vector":              { size: [2, 1, 2], index: 38 },
  "Rotation":            { size: [2, 1, 2], index: 42 },
  "Get Number":          { size: [2, 1, 1], index: 46 },
  "Get Vector":          { size: [2, 1, 1], index: 48 },
  "Get Rotation":        { size: [2, 1, 1], index: 50 },
  "Get Truth":           { size: [2, 1, 1], index: 52 },
  "Get Object":          { size: [2, 1, 1], index: 54 },
  "Get Constraint":      { size: [2, 1, 1], index: 56 },
  "Set Number List":     { size: [2, 1, 2], index: 58 },
  "Set Vector List":     { size: [2, 1, 2], index: 62 },
  "Set Rotation List":   { size: [2, 1, 2], index: 66 },
  "Set Truth List":      { size: [2, 1, 2], index: 70 },
  "Set Object List":     { size: [2, 1, 2], index: 74 },
  "Set Constraint List": { size: [2, 1, 2], index: 78 },
  "List Number":         { size: [2, 1, 2], index: 82 },
  "List Object":         { size: [2, 1, 2], index: 86 },
  "Negate":              { size: [2, 1, 1], index: 90 },
  "Add Numbers":         { size: [2, 1, 2], index: 92 },
  "Add Vectors":         { size: [2, 1, 2], index: 96 },
  "Subtract Numbers":    { size: [2, 1, 2], index: 100 },
  "Subtract Vectors":    { size: [2, 1, 2], index: 104 },
  "Multiply":            { size: [2, 1, 2], index: 108 },
  "Scale":               { size: [2, 1, 2], index: 112 },
  "Rotate":              { size: [2, 1, 2], index: 116 },
  "Combine":             { size: [2, 1, 2], index: 120 },
  "Divide":              { size: [2, 1, 2], index: 124 },
  "Less Than":           { size: [2, 1, 2], index: 128 },
  "Equal Numbers":       { size: [2, 1, 2], index: 132 },
  "Equal Vectors":       { size: [2, 1, 2], index: 136 },
  "Equal Objects":       { size: [2, 1, 2], index: 140 },
  "NOT":                 { size: [2, 1, 1], index: 144 },
  "AND":                 { size: [2, 1, 2], index: 146 },
  "Make Vector":         { size: [2, 1, 3], index: 150 },
  "Break Vector":        { size: [2, 1, 3], index: 156 },
  "Make Rotation":       { size: [2, 1, 3], index: 162 },
  "Random":              { size: [2, 1, 2], index: 168 },
  "Modulo":              { size: [2, 1, 2], index: 172 },
  "Min":                 { size: [2, 1, 2], index: 176 },
  "Max":                 { size: [2, 1, 2], index: 180 },
  "Round":               { size: [2, 1, 1], index: 184 },
  "Floor":               { size: [2, 1, 1], index: 186 },
  "Ceiling":             { size: [2, 1, 1], index: 188 },
  "Distance":            { size: [2, 1, 2], index: 190 },
  "LERP":                { size: [2, 1, 3], index: 194 },
  "Axis Angle":          { size: [2, 1, 2], index: 200 },
  "Look Rotation":       { size: [2, 1, 2], index: 204 },
  "Line vs Plane":       { size: [2, 1, 4], index: 208 },
  "Screen to World":     { size: [2, 1, 2], index: 216 },
  "Screen Size":         { size: [2, 1, 2], index: 220 },
  "Accelerometer":       { size: [2, 1, 2], index: 224 },
  "Raycast":             { size: [2, 1, 3], index: 228 },
  "If":                  { size: [2, 1, 2], index: 234 },
  "Play Sensor":         { size: [2, 1, 2], index: 238 },
  "Touch Sensor":        { size: [2, 1, 3], index: 242 },
  "Swipe Sensor":        { size: [2, 1, 2], index: 248 },
  "Win":                 { size: [2, 1, 2], index: 252 },
  "Lose":                { size: [2, 1, 2], index: 256 },
  "Set Score":           { size: [2, 1, 2], index: 260 },
  "Play Sound":          { size: [2, 1, 2], index: 264 },
  "Set Camera":          { size: [2, 1, 3], index: 268 },
  "Set Light":           { size: [2, 1, 2], index: 274 },
  "Get Position":        { size: [2, 1, 2], index: 278 },
  "Set Position":        { size: [2, 1, 3], index: 282 },
  "Get Velocity":        { size: [2, 1, 2], index: 288 },
  "Set Velocity":        { size: [2, 1, 3], index: 292 },
  "Add Force":           { size: [2, 1, 4], index: 298 },
  "Set Visible":         { size: [2, 1, 2], index: 306 },
  "Set Locked":          { size: [2, 1, 3], index: 310 },
  "Create Object":       { size: [2, 1, 2], index: 316 },
  "Destroy Object":      { size: [2, 1, 2], index: 320 },
  "Set Gravity":         { size: [2, 1, 2], index: 324 },
  "Set Mass":            { size: [2, 1, 2], index: 328 },
  "Set Friction":        { size: [2, 1, 2], index: 332 },
  "Set Bounciness":      { size: [2, 1, 2], index: 336 },
  "Add Constraint":      { size: [2, 1, 3], index: 340 },
  "Linear Limits":       { size: [2, 1, 3], index: 346 },
  "Angular Limits":      { size: [2, 1, 3], index: 352 },
  "Linear Spring":       { size: [2, 1, 3], index: 358 },
  "Angular Spring":      { size: [2, 1, 3], index: 364 },
  "Linear Motor":        { size: [2, 1, 3], index: 370 },
  "Angular Motor":       { size: [2, 1, 3], index: 376 },
  "Volume Pitch":        { size: [2, 1, 3], index: 391 },
  "Stop Sound":          { size: [2, 1, 2], index: 397 },
  "Collision":           { size: [2, 1, 4], index: 401 },
  "Box Art Sensor":      { size: [2, 1, 2], index: 409 },
  "Sin":                 { size: [2, 1, 1], index: 413 },
  "OR":                  { size: [2, 1, 2], index: 417 },
  "Equal Truths":        { size: [2, 1, 2], index: 421 },
  "Set Number":          { size: [2, 1, 1], index: 428 },
  "Set Vector":          { size: [2, 1, 1], index: 430 },
  "Set Rotation":        { size: [2, 1, 1], index: 432 },
  "Set Truth":           { size: [2, 1, 1], index: 434 },
  "Set Object":          { size: [2, 1, 1], index: 436 },
  "Set Constraint":      { size: [2, 1, 1], index: 438 },
  "Inverse":             { size: [2, 1, 1], index: 440 },
  "Break Rotation":      { size: [2, 1, 3], index: 442 },
  "True":                { size: [2, 1, 1], index: 449 },
  "False":               { size: [2, 1, 1], index: 451 },
  "Cos":                 { size: [2, 1, 1], index: 453 },
  "Absolute":            { size: [2, 1, 1], index: 455 },
  "Power":               { size: [2, 1, 2], index: 457 },
  "List Vector":         { size: [2, 1, 2], index: 461 },
  "List Rotation":       { size: [2, 1, 2], index: 465 },
  "List Truth":          { size: [2, 1, 2], index: 469 },
  "List Constraint":     { size: [2, 1, 2], index: 473 },
  "World To Screen":     { size: [2, 1, 2], index: 477 },
  "Greater Than":        { size: [2, 1, 2], index: 481 },
  "Random Seed":         { size: [2, 1, 2], index: 485 },
  "Get Size":            { size: [2, 1, 2], index: 489 },
  "Increase Number":     { size: [2, 1, 1], index: 556 },
  "Decrease Number":     { size: [2, 1, 1], index: 558 },
  "Loop":                { size: [2, 1, 2], index: 560 },
  "Current Frame":       { size: [2, 1, 1], index: 564 },
  "Late Update":         { size: [2, 1, 2], index: 566 },
  "Dot Product":         { size: [2, 1, 2], index: 570 },
  "Cross Product":       { size: [2, 1, 2], index: 574 },
  "Normalize":           { size: [2, 1, 1], index: 578 },
  "Logarithm":           { size: [2, 1, 2], index: 580 },
  "Menu Item":           { size: [2, 1, 2], index: 584 },
  "Button":              { size: [2, 1, 2], index: 588 },
  "Joystick":            { size: [2, 1, 2], index: 592 },
};

export const Partial = {
  "L2R":                 { size: [1, 1, 1], index: 9 },
  "Multi In":            { size: [1, 1, 1], index: 10 },
  "Multi Out":           { size: [1, 1, 1], index: 11 },
  "Multi In E":          { size: [1, 1, 1], index: 12 },
  "Multi Out E":         { size: [1, 1, 1], index: 13 },
  "This Object":         { size: [1, 1, 1], index: 14 },
  "IO":                  { size: [1, 1, 1], index: 596 },
};

export const Builtin = {
  "Swipe Chick":         { size: [1, 1, 1], index: 383 },
  "Goal":                { size: [1, 1, 1], index: 389 },
  "Button":              { size: [1, 1, 1], index: 390 },
  "Tilt Ball":           { size: [1, 1, 1], index: 427 },
  "Motor":               { size: [1, 1, 1], index: 527, variations: 3 },
  "Slider":              { size: [1, 1, 1], index: 530, variations: 3 },
  "Button":              { size: [1, 1, 1], index: 553 },
  "Wheel":               { size: [1, 1, 1], index: 534 },
  "Dash Cat":            { size: [1, 1, 1], index: 535 },
  "Tap Dino":            { size: [1, 1, 1], index: 537 },
  "Red Dino":            { size: [1, 1, 1], index: 538 },
  "Butterfly":           { size: [1, 1, 1], index: 539 },
  "Camera Orbit":        { size: [2, 1, 2], index: 540 },
  "Slider Script":       { size: [1, 1, 1], index: 544 },
};

export const Block = Object.freeze({
  __proto__: null,
  Empty,
  Folder,
  Stock,
  Script,
  Partial,
  Builtin,
});
