import {
  Vector3Uint16,
} from "./vector.js";

function vec(x, y, z) {
  return Vector3Uint16.from({ x, y, z });
}

export const Blocks = [
  { name: "Empty",                index:   0, size: vec(1, 1, 1) },
  { name: "Stone Block",          index:   1, size: vec(1, 1, 1) },
  { name: "Bricks",               index:   2, size: vec(1, 1, 1) },
  { name: "Grass",                index:   3, size: vec(1, 1, 1) },
  { name: "Grass",                index:   4, size: vec(1, 1, 1) },
  { name: "Dirt",                 index:   5, size: vec(1, 1, 1) },
  { name: "Wood",                 index:   6, size: vec(1, 1, 1) },
  { name: "Wood",                 index:   7, size: vec(1, 1, 1) },
  { name: "Wood",                 index:   8, size: vec(1, 1, 1) },
  { name: "L2R",                  index:   9, size: vec(1, 1, 1) },
  { name: "Multi In",             index:  10, size: vec(1, 1, 1) },
  { name: "Multi Out",            index:  11, size: vec(1, 1, 1) },
  { name: "Multi In E",           index:  12, size: vec(1, 1, 1) },
  { name: "Multi Out E",          index:  13, size: vec(1, 1, 1) },
  { name: "This Object",          index:  14, size: vec(1, 1, 1) },
  { name: "Comment",              index:  15, size: vec(1, 1, 1) },
  { name: "Inspect Number",       index:  16, size: vec(2, 1, 2) },
  { name: "Inspect Vector",       index:  20, size: vec(2, 1, 2) },
  { name: "Inspect Rotation",     index:  24, size: vec(2, 1, 2) },
  { name: "Inspect Truth",        index:  28, size: vec(2, 1, 2) },
  { name: "Inspect Object",       index:  32, size: vec(2, 1, 2) },
  { name: "Number",               index:  36, size: vec(2, 1, 1) },
  { name: "Vector",               index:  38, size: vec(2, 1, 2) },
  { name: "Rotation",             index:  42, size: vec(2, 1, 2) },
  { name: "Get Number",           index:  46, size: vec(2, 1, 1) },
  { name: "Get Vector",           index:  48, size: vec(2, 1, 1) },
  { name: "Get Rotation",         index:  50, size: vec(2, 1, 1) },
  { name: "Get Truth",            index:  52, size: vec(2, 1, 1) },
  { name: "Get Object",           index:  54, size: vec(2, 1, 1) },
  { name: "Get Constraint",       index:  56, size: vec(2, 1, 1) },
  { name: "Set Number List",      index:  58, size: vec(2, 1, 2) },
  { name: "Set Vector List",      index:  62, size: vec(2, 1, 2) },
  { name: "Set Rotation List",    index:  66, size: vec(2, 1, 2) },
  { name: "Set Truth List",       index:  70, size: vec(2, 1, 2) },
  { name: "Set Object List",      index:  74, size: vec(2, 1, 2) },
  { name: "Set Constraint List",  index:  78, size: vec(2, 1, 2) },
  { name: "List Number",          index:  82, size: vec(2, 1, 2) },
  { name: "List Object",          index:  86, size: vec(2, 1, 2) },
  { name: "Negate",               index:  90, size: vec(2, 1, 1) },
  { name: "Add Numbers",          index:  92, size: vec(2, 1, 2) },
  { name: "Add Vectors",          index:  96, size: vec(2, 1, 2) },
  { name: "Subtract Numbers",     index: 100, size: vec(2, 1, 2) },
  { name: "Subtract Vectors",     index: 104, size: vec(2, 1, 2) },
  { name: "Multiply",             index: 108, size: vec(2, 1, 2) },
  { name: "Scale",                index: 112, size: vec(2, 1, 2) },
  { name: "Rotate",               index: 116, size: vec(2, 1, 2) },
  { name: "Combine",              index: 120, size: vec(2, 1, 2) },
  { name: "Divide",               index: 124, size: vec(2, 1, 2) },
  { name: "Less Than",            index: 128, size: vec(2, 1, 2) },
  { name: "Equal Numbers",        index: 132, size: vec(2, 1, 2) },
  { name: "Equal Vectors",        index: 136, size: vec(2, 1, 2) },
  { name: "Equal Objects",        index: 140, size: vec(2, 1, 2) },
  { name: "NOT",                  index: 144, size: vec(2, 1, 1) },
  { name: "AND",                  index: 146, size: vec(2, 1, 2) },
  { name: "Make Vector",          index: 150, size: vec(2, 1, 3) },
  { name: "Break Vector",         index: 156, size: vec(2, 1, 3) },
  { name: "Make Rotation",        index: 162, size: vec(2, 1, 3) },
  { name: "Random",               index: 168, size: vec(2, 1, 2) },
  { name: "Modulo",               index: 172, size: vec(2, 1, 2) },
  { name: "Min",                  index: 176, size: vec(2, 1, 2) },
  { name: "Max",                  index: 180, size: vec(2, 1, 2) },
  { name: "Round",                index: 184, size: vec(2, 1, 1) },
  { name: "Floor",                index: 186, size: vec(2, 1, 1) },
  { name: "Ceiling",              index: 188, size: vec(2, 1, 1) },
  { name: "Distance",             index: 190, size: vec(2, 1, 2) },
  { name: "LERP",                 index: 194, size: vec(2, 1, 3) },
  { name: "Axis Angle",           index: 200, size: vec(2, 1, 2) },
  { name: "Look Rotation",        index: 204, size: vec(2, 1, 2) },
  { name: "Line vs Plane",        index: 208, size: vec(2, 1, 4) },
  { name: "Screen to World",      index: 216, size: vec(2, 1, 2) },
  { name: "Screen Size",          index: 220, size: vec(2, 1, 2) },
  { name: "Accelerometer",        index: 224, size: vec(2, 1, 2) },
  { name: "Raycast",              index: 228, size: vec(2, 1, 3) },
  { name: "If",                   index: 234, size: vec(2, 1, 2) },
  { name: "Play Sensor",          index: 238, size: vec(2, 1, 2) },
  { name: "Touch Sensor",         index: 242, size: vec(2, 1, 3) },
  { name: "Swipe Sensor",         index: 248, size: vec(2, 1, 2) },
  { name: "Win",                  index: 252, size: vec(2, 1, 2) },
  { name: "Lose",                 index: 256, size: vec(2, 1, 2) },
  { name: "Set Score",            index: 260, size: vec(2, 1, 2) },
  { name: "Play Sound",           index: 264, size: vec(2, 1, 2) },
  { name: "Set Camera",           index: 268, size: vec(2, 1, 3) },
  { name: "Set Light",            index: 274, size: vec(2, 1, 2) },
  { name: "Get Position",         index: 278, size: vec(2, 1, 2) },
  { name: "Set Position",         index: 282, size: vec(2, 1, 3) },
  { name: "Get Velocity",         index: 288, size: vec(2, 1, 2) },
  { name: "Set Velocity",         index: 292, size: vec(2, 1, 3) },
  { name: "Add Force",            index: 298, size: vec(2, 1, 4) },
  { name: "Set Visible",          index: 306, size: vec(2, 1, 2) },
  { name: "Set Locked",           index: 310, size: vec(2, 1, 3) },
  { name: "Create Object",        index: 316, size: vec(2, 1, 2) },
  { name: "Destroy Object",       index: 320, size: vec(2, 1, 2) },
  { name: "Set Gravity",          index: 324, size: vec(2, 1, 2) },
  { name: "Set Mass",             index: 328, size: vec(2, 1, 2) },
  { name: "Set Friction",         index: 332, size: vec(2, 1, 2) },
  { name: "Set Bounciness",       index: 336, size: vec(2, 1, 2) },
  { name: "Add Constraint",       index: 340, size: vec(2, 1, 3) },
  { name: "Linear Limits",        index: 346, size: vec(2, 1, 3) },
  { name: "Angular Limits",       index: 352, size: vec(2, 1, 3) },
  { name: "Linear Spring",        index: 358, size: vec(2, 1, 3) },
  { name: "Angular Spring",       index: 364, size: vec(2, 1, 3) },
  { name: "Linear Motor",         index: 370, size: vec(2, 1, 3) },
  { name: "Angular Motor",        index: 376, size: vec(2, 1, 3) },
  { name: "Folder Unknown",       index: 382, size: vec(1, 1, 1) },
  { name: "Swipe Chick",          index: 383, size: vec(1, 1, 1) },
  { name: "Dirt Slab",            index: 384, size: vec(1, 1, 1) },
  { name: "Steel",                index: 385, size: vec(1, 1, 1) },
  { name: "Arch",                 index: 386, size: vec(1, 2, 1) },
  { name: "Box",                  index: 388, size: vec(1, 1, 1) },
  { name: "Goal",                 index: 389, size: vec(1, 1, 1) },
  { name: "Button",               index: 390, size: vec(1, 1, 1) },
  { name: "Volume Pitch",         index: 391, size: vec(2, 1, 3) },
  { name: "Stop Sound",           index: 397, size: vec(2, 1, 2) },
  { name: "Collision",            index: 401, size: vec(2, 1, 4) },
  { name: "Box Art Sensor",       index: 409, size: vec(2, 1, 2) },
  { name: "Sin",                  index: 413, size: vec(2, 1, 1) },
  { name: "Folder Empty",         index: 415, size: vec(1, 1, 1) },
  { name: "Folder Locked",        index: 416, size: vec(1, 1, 1) },
  { name: "OR",                   index: 417, size: vec(2, 1, 2) },
  { name: "Equal Truths",         index: 421, size: vec(2, 1, 2) },
  { name: "Physics Box",          index: 425, size: vec(1, 1, 1) },
  { name: "Physics Sphere",       index: 426, size: vec(1, 1, 1) },
  { name: "Tilt Ball",            index: 427, size: vec(1, 1, 1) },
  { name: "Set Number",           index: 428, size: vec(2, 1, 1) },
  { name: "Set Vector",           index: 430, size: vec(2, 1, 1) },
  { name: "Set Rotation",         index: 432, size: vec(2, 1, 1) },
  { name: "Set Truth",            index: 434, size: vec(2, 1, 1) },
  { name: "Set Object",           index: 436, size: vec(2, 1, 1) },
  { name: "Set Constraint",       index: 438, size: vec(2, 1, 1) },
  { name: "Inverse",              index: 440, size: vec(2, 1, 1) },
  { name: "Break Rotation",       index: 442, size: vec(2, 1, 3) },
  { name: "Pass Through",         index: 448, size: vec(1, 1, 1) },
  { name: "True",                 index: 449, size: vec(2, 1, 1) },
  { name: "False",                index: 451, size: vec(2, 1, 1) },
  { name: "Cos",                  index: 453, size: vec(2, 1, 1) },
  { name: "Absolute",             index: 455, size: vec(2, 1, 1) },
  { name: "Power",                index: 457, size: vec(2, 1, 2) },
  { name: "List Vector",          index: 461, size: vec(2, 1, 2) },
  { name: "List Rotation",        index: 465, size: vec(2, 1, 2) },
  { name: "List Truth",           index: 469, size: vec(2, 1, 2) },
  { name: "List Constraint",      index: 473, size: vec(2, 1, 2) },
  { name: "World To Screen",      index: 477, size: vec(2, 1, 2) },
  { name: "Greater Than",         index: 481, size: vec(2, 1, 2) },
  { name: "Random Seed",          index: 485, size: vec(2, 1, 2) },
  { name: "Get Size",             index: 489, size: vec(2, 1, 2) },
  { name: "Dirt",                 index: 493, size: vec(1, 1, 1) },
  { name: "Flowers",              index: 494, size: vec(1, 1, 1) },
  { name: "Foliage",              index: 495, size: vec(1, 1, 1) },
  { name: "Foliage",              index: 496, size: vec(1, 1, 1) },
  { name: "Foliage Top",          index: 497, size: vec(1, 1, 1) },
  { name: "Foliage Bottom",       index: 498, size: vec(1, 1, 1) },
  { name: "Foliage Slab",         index: 499, size: vec(1, 1, 1) },
  { name: "Shrub",                index: 500, size: vec(1, 1, 1) },
  { name: "Stone",                index: 501, size: vec(1, 1, 1) },
  { name: "Stone",                index: 502, size: vec(1, 1, 1) },
  { name: "Stone Top",            index: 503, size: vec(1, 1, 1) },
  { name: "Stone Bottom",         index: 504, size: vec(1, 1, 1) },
  { name: "Stone Slab",           index: 505, size: vec(1, 1, 1) },
  { name: "Stone Pillar",         index: 506, size: vec(1, 1, 1) },
  { name: "Stone Half",           index: 507, size: vec(1, 1, 1) },
  { name: "Wood Half",            index: 508, size: vec(1, 1, 1) },
  { name: "Wood Half",            index: 509, size: vec(1, 1, 1) },
  { name: "Wood Half",            index: 510, size: vec(1, 1, 1) },
  { name: "Wood Half",            index: 511, size: vec(1, 1, 1) },
  { name: "Stick",                index: 512, size: vec(1, 1, 1) },
  { name: "Stick",                index: 513, size: vec(1, 1, 1) },
  { name: "Stick",                index: 514, size: vec(1, 1, 1) },
  { name: "Stick",                index: 515, size: vec(1, 1, 1) },
  { name: "Stick",                index: 516, size: vec(1, 1, 1) },
  { name: "Stick",                index: 517, size: vec(1, 1, 1) },
  { name: "Stick",                index: 518, size: vec(1, 1, 1) },
  { name: "Stick",                index: 519, size: vec(1, 1, 1) },
  { name: "Stick",                index: 520, size: vec(1, 1, 1) },
  { name: "Stick",                index: 521, size: vec(1, 1, 1) },
  { name: "Stick",                index: 522, size: vec(1, 1, 1) },
  { name: "Stick",                index: 523, size: vec(1, 1, 1) },
  { name: "Stick",                index: 524, size: vec(1, 1, 1) },
  { name: "Stick",                index: 525, size: vec(1, 1, 1) },
  { name: "Stick",                index: 526, size: vec(1, 1, 1) },
  { name: "Motor",                index: 527, size: vec(1, 1, 1) },
  { name: "Motor",                index: 528, size: vec(1, 1, 1) },
  { name: "Motor",                index: 529, size: vec(1, 1, 1) },
  { name: "Slider",               index: 530, size: vec(1, 1, 1) },
  { name: "Slider",               index: 531, size: vec(1, 1, 1) },
  { name: "Slider",               index: 532, size: vec(1, 1, 1) },
  { name: "Button",               index: 533, size: vec(1, 1, 1) },
  { name: "Wheel",                index: 534, size: vec(1, 1, 1) },
  { name: "Dash Cat",             index: 535, size: vec(1, 1, 1) },
  { name: "Marker",               index: 536, size: vec(1, 1, 1) },
  { name: "Tap Dino",             index: 537, size: vec(1, 1, 1) },
  { name: "Red Dino",             index: 538, size: vec(1, 1, 1) },
  { name: "Butterfly",            index: 539, size: vec(1, 1, 1) },

  // the order of this block is not "normal"
  // { name: "Camera Orbit",         index: 540, size: vec(2, 1, 2) },
  { name: "Camera Orbit",         index: 540, size: vec(2, 1, 2), data: [540, 542, 543, 541] },

  { name: "Slider Script",        index: 544, size: vec(1, 1, 1) },
  { name: "Script Block",         index: 545, size: vec(1, 1, 1) },
  { name: "Sphere",               index: 546, size: vec(1, 1, 1) },
  { name: "Slate",                index: 547, size: vec(1, 1, 1) },
  { name: "Slate",                index: 548, size: vec(1, 1, 1) },
  { name: "Slate NE",             index: 549, size: vec(1, 1, 1) },
  { name: "Slate NW",             index: 550, size: vec(1, 1, 1) },
  { name: "Slate SE",             index: 551, size: vec(1, 1, 1) },
  { name: "Slate SW",             index: 552, size: vec(1, 1, 1) },
  { name: "Slate Top",            index: 553, size: vec(1, 1, 1) },
  { name: "Slate Bottom",         index: 554, size: vec(1, 1, 1) },
  { name: "Particle",             index: 555, size: vec(1, 1, 1) },
  { name: "Increase Number",      index: 556, size: vec(2, 1, 1) },
  { name: "Decrease Number",      index: 558, size: vec(2, 1, 1) },
  { name: "Loop",                 index: 560, size: vec(2, 1, 2) },
  { name: "Current Frame",        index: 564, size: vec(2, 1, 1) },
  { name: "Late Update",          index: 566, size: vec(2, 1, 2) },
  { name: "Dot Product",          index: 570, size: vec(2, 1, 2) },
  { name: "Cross Product",        index: 574, size: vec(2, 1, 2) },
  { name: "Normalize",            index: 578, size: vec(2, 1, 1) },
  { name: "Logarithm",            index: 580, size: vec(2, 1, 2) },
  { name: "Menu Item",            index: 584, size: vec(2, 1, 2) },
  { name: "Button",               index: 588, size: vec(2, 1, 2) },
  { name: "Joystick",             index: 592, size: vec(2, 1, 2) },
  { name: "IO",                   index: 596, size: vec(1, 1, 1) }
];
